#define { author-version: "2.24.1"; }

#define { outercurve-publickeytoken: "1e373a58e25250cb"; }

#define { deps-publickeytoken: "${outercurve-publickeytoken}"; }

#define { glib-dep-version: "2.32.3"; }

#define { glib-dep-publickeytoken: "${deps-publickeytoken}"; }

#define { libintl-dep-version: "0.18.1"; }

#define { libintl-dep-publickeytoken: "${deps-publickeytoken}"; }

#define { libpng-dep-version: "1.5.10"; }

#define { libpng-dep-publickeytoken: "${deps-publickeytoken}"; }
